config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #API "path", to: "folder#file", as: :url_alias (blogs_path(1) => "/blogs/1")
  devise_for :users
  get "/blogs/view" , to: "blogs#view", as: :blogs_view
  resources :blogs

  root "blogs#index"

  # for api
  mount Blogs::Api => "/"
  mount Users::Api => "/"
end

app/models/blog.rb
class Blog < ApplicationRecord

  has_rich_text :content
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.where(is_public: true).order(:created_at).reverse
    if params[:search]  # checks for nil value
      key = params[:search].strip
      if key.length>0
        @blogs.select! do |blog|
          blog.title.include?(key) or blog.content.to_plain_text.include?(key)
        end
      else
        redirect_to root_path, alert: "Enter text for performing search!!"
      end
    end
    # render json: @blogs
  end

  # to view private blogs
  def view
    @blogs = Blog.where(user_id: current_user[:id]).order(:created_at).reverse
    if params[:search]  # checks for nil value
      key = params[:search].strip
      if key.length>0
        @blogs.select! do |blog|
          blog.title.include?(key) or blog.content.to_plain_text.include?(key)
        end
      else
        redirect_to blogs_view_path, alert: "Enter text for performing search!!"
      end
    end
  end

  def show
    # @blog = Blog.find(params[:id])
    if !@blog[:is_public]
      if current_user.nil? or current_user[:id]!=@blog[:user_id]
        redirect_to blogs_path, alert: "You don't have access to this blog!!"
      end
    end
  end

  def new
    # create a object in memo and pass it to html to fill
    @blog = current_user.blogs.build
  end

  def edit
    # @blog = Blog.find(params[:id])
    if current_user[:id]!=@blog[:user_id]
      redirect_to blog_path, alert: "You dont have permission to modify this blog!!"
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to @blog
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    # @blog = Blog.find(params[:id])
    if current_user[:id]==@blog[:user_id] and @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @blog = Blog.find(params[:id])
    msg = "You dont have permission to Delete this blog!!"
    if current_user[:id]==@blog[:user_id]
      @blog.destroy
      msg = "Succefully Deleted the Blog"
    end
    redirect_to blogs_path, notice: msg
  end

  private

  def blog_params
    # check if the params has the following data
    params.require(:blog).permit(:title, :content, :is_public)
  end

  def set_blog
      @blog = Blog.find(params[:id])
    rescue
      redirect_to blogs_path
  end

end

app/views/blogs/_form.html.erb
<%= form_with model: blog do |form| %>
<% if form.object.errors.any? %>
<div>
    <% form.object.errors.full_messages.each do |message| %>
    <div><%= message %></div>
    <% end %>
</div>
<% end %>
<div class="field">
    <%= form.label :title%>
    <%= form.text_field :title%>
</div>
<div class="field">
    <%= form.label :content%>
    <%= form.rich_text_area :content%>
</div>

<div class="field">
    <%= form.label :is_public %>
    <%= form.check_box :is_public, {}, "true", "false" %>
</div>

<div class="actions">
    <%= form.button request.original_url.include?("edit") ? "Update" : "Create Blog", :class => "btn" %>
</div>
<% end %>

app/views/blogs/edit.html.erb
<h1> Edit Page </h1>

<%= render partial: "form", locals: {blog: @blog} %>
<%= button_to "Delete", @blog, method: :delete, data: {turbo_confirm: "Are you Sure?"}, :class => "actions btn"%>

app/views/blogs/index.html.erb
<h1>Blog App</h1>

<% if user_signed_in? %>
    <h3> List of Accessible Blogs </h3>
<% else %>
    <h3> List of Public Blogs </h3>
<% end %>

<ul class="list">
    <% @blogs.each do |blog| %>
        <li class="list-item">
            <%= link_to blog_path(blog.id) do%>
            <span>
                <%= blog.title  %>
            </span>
            <span>
                <%= "- " + blog.user[:display_name] %>
            </span>
            <% end %>
        </li>
    <% end %>
</ul>

app/views/blogs/new.html.erb
<h1> Create a new Blog </h1>

<%= render partial: "form", locals: {blog: @blog} %>

app/views/blogs/show.html.erb
<div class="blog">
    <h2 class="title"> <%= @blog.title %> </h2>
    <p> <%= @blog.content %> </p>
    <h4 class="author">By, <%= @blog.user[:display_name] %></h4>
</div>

<div>
    <% if current_user and current_user[:user_name]==@blog.user[:user_name] %>
        <%= link_to "Edit", edit_blog_path %>
    <% end %>
</div>

app/views/blogs/view.html.erb
<h3> List of Private Blogs </h3>

<ul class="list">
    <% @blogs.each do |blog| %>
        <li class="list-item">
            <%= link_to blog_path(blog.id) do%>
            <span>
                <%= blog.title  %>
            </span>
            <p>
                <%= blog.content.to_plain_text.truncate(30) %>
            </p>
            <span>
                <%= "by, " + blog.user[:display_name] %>
            </span>
            <% end %>
        </li>
    <% end %>
</ul>