config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #API "path", to: "folder#file", as: :url_alias (blogs_path(1) => "/blogs/1")
  devise_for :users
  get "/blogs/view" , to: "blogs#view", as: :blogs_view
  resources :blogs

  root "blogs#index"

  # for api
  mount Blogs::Api => "/"
  mount Users::Api => "/"
end

app/views/layouts/_navbar.html.erb
<div class="top">
    <%= link_to "Home", root_path %>
    <% if user_signed_in? %>
        <%= link_to "Edit Profile", edit_user_registration_path %>
        <%= link_to "My Blogs", blogs_view_path %>
        <%= link_to "Create a new Blog", new_blog_path %>
        <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn' %>
    <% else %>
        <%= link_to "Sign Up", new_user_registration_path %>
        <%= link_to "Log In", new_user_session_path %>
    <% end %>
</div>
<div class ="bottom">
    <%= form_tag request.original_url, :method => "get" do %>
        <%= label_tag(:search, "Type a key word: ") %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag("Search", :name=>nil, :class => "search-btn")%>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="sidenav">
      <%= render partial: "layouts/navbar" %>
    </div>
    <div class="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>